# -*- coding: utf-8 -*-
"""Validador de Documentação.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mwY9GZgcj3ZISBPEEdLusD9FiUHHmnio
"""

#INSTALANDO BIBLIOTECAS DE LEITURA DE DOCUMENTOS
! sudo apt install tesseract-ocr 
! pip install pytesseract

import pytesseract
import shutil
import os
import random
try:
 from PIL import Image
except ImportError:
 import Image

#INSTALANDO BIBLIOTECAS PARA UTILIZAÇÃO DE API'S
!  pip install flask flask-jsonpify flask-sqlalchemy flask-restful

from flask import Flask, request, jsonify
from flask_restful import Resource, Api
from sqlalchemy import create_engine
from json import dumps

from google.colab import files
uploaded = files.upload()

image_path_in_colab = 'businessvaluation1.png'

extractedInformation = pytesseract.image_to_string(Image.open(image_path_in_colab))

print (extractedInformation)

business = 'Advisor'
decore = 'Empresarial'

if business in extractedInformation:
  print("DOCUMENTO DO TIPO BUSINESS VALUATION VÁLIDO!")
if decore in extractedInformation:
  print("DOCUMENTO DO TIPO DECORE VÁLIDO!")
else:
  print("DOCUMENTO INVÁLIDO!")